/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;
import javax.swing.JOptionPane;

/**
 *
 * @author Rainmaker
 */
public class BreadthFirstSearch extends javax.swing.JFrame {
    private BFS BFS;
    int matrixSize;

    /**
     * Creates new form BreadthFirstSearch
     */
    public BreadthFirstSearch() {
        initComponents();
        setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        ta_OutputMatrix1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        m_taInputMatrix1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_taInputMatrix = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        m_taOutputGraph = new javax.swing.JTextArea();
        m_btnSetMatrixSize = new javax.swing.JButton();
        m_tbMatrixSize = new javax.swing.JTextField();
        m_btnSetMatrixValues = new javax.swing.JButton();
        m_btnGetBFS = new javax.swing.JButton();

        ta_OutputMatrix1.setEditable(false);
        ta_OutputMatrix1.setColumns(20);
        ta_OutputMatrix1.setRows(5);
        jScrollPane3.setViewportView(ta_OutputMatrix1);

        m_taInputMatrix1.setEditable(false);
        m_taInputMatrix1.setColumns(20);
        m_taInputMatrix1.setLineWrap(true);
        m_taInputMatrix1.setRows(5);
        jScrollPane4.setViewportView(m_taInputMatrix1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        m_taInputMatrix.setEditable(false);
        m_taInputMatrix.setColumns(20);
        m_taInputMatrix.setLineWrap(true);
        m_taInputMatrix.setRows(5);
        jScrollPane1.setViewportView(m_taInputMatrix);

        m_taOutputGraph.setEditable(false);
        m_taOutputGraph.setColumns(20);
        m_taOutputGraph.setRows(5);
        jScrollPane2.setViewportView(m_taOutputGraph);

        m_btnSetMatrixSize.setText("Set Matrix Size");
        m_btnSetMatrixSize.setMinimumSize(new java.awt.Dimension(25, 29));
        m_btnSetMatrixSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnSetMatrixSizeActionPerformed(evt);
            }
        });

        m_btnSetMatrixValues.setText("Set Values");
        m_btnSetMatrixValues.setMinimumSize(new java.awt.Dimension(25, 29));
        m_btnSetMatrixValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnSetMatrixValuesActionPerformed(evt);
            }
        });

        m_btnGetBFS.setText("Get BFS");
        m_btnGetBFS.setMinimumSize(new java.awt.Dimension(25, 29));
        m_btnGetBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnGetBFSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_tbMatrixSize, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_btnSetMatrixSize, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_btnGetBFS, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_btnSetMatrixValues, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_tbMatrixSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_btnSetMatrixValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_btnSetMatrixSize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_btnGetBFS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void m_btnSetMatrixSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnSetMatrixSizeActionPerformed
      if(checkValue()){
          //BFS.setAdjacenyMatrix(void);
          m_taInputMatrix.enableInputMethods(true);
          
      }else
      {
          String errorMessage = "MatrixX and MatrixY, must be greater than or equal to zero";
          JOptionPane.showMessageDialog(null, errorMessage,"Error",JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_m_btnSetMatrixSizeActionPerformed

    private void m_btnGetBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnGetBFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_btnGetBFSActionPerformed

    private void m_btnSetMatrixValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnSetMatrixValuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_btnSetMatrixValuesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BreadthFirstSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BreadthFirstSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BreadthFirstSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BreadthFirstSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BreadthFirstSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton m_btnGetBFS;
    private javax.swing.JButton m_btnSetMatrixSize;
    private javax.swing.JButton m_btnSetMatrixValues;
    private javax.swing.JTextArea m_taInputMatrix;
    private javax.swing.JTextArea m_taInputMatrix1;
    private javax.swing.JTextArea m_taOutputGraph;
    private javax.swing.JTextField m_tbMatrixSize;
    private javax.swing.JTextArea ta_OutputMatrix1;
    // End of variables declaration//GEN-END:variables

    private void setup() {
        BFS = new BFS();
    }
    
    private boolean checkValue(){
        matrixSize = Integer.parseInt(m_tbMatrixSize.getText());
        if(matrixSize >=1)
            return true;
        else 
            return false;     
    }
    
    private void getMatrix(){
        String str = m_taInputMatrix.getText();
        int strLength = str.length();

    }
}
