/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;
import javax.swing.JOptionPane;

/**
 *
 * @author Rainmaker
 */
public class BreadthFirstSearch extends javax.swing.JFrame {
    private BFS BFS;
    int matrixY;
    int matrixX;

    /**
     * Creates new form BreadthFirstSearch
     */
    public BreadthFirstSearch() {
        initComponents();
        BFS = new BFS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ta_OutputMatrix = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_taInputMatrix = new javax.swing.JTextArea();
        tb_MatrixSizeX = new javax.swing.JTextField();
        tb_MatrixSizeY = new javax.swing.JTextField();
        lbl_MatrixY = new javax.swing.JLabel();
        lbl_MatrixX = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_taInputMatrix = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_OutputMatrix = new javax.swing.JTextArea();
        btn_setMatrixSize = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_setMatrixSize1 = new javax.swing.JButton();

        ta_OutputMatrix.setEditable(false);
        ta_OutputMatrix.setColumns(20);
        ta_OutputMatrix.setRows(5);
        jScrollPane2.setViewportView(ta_OutputMatrix);

        m_taInputMatrix.setEditable(false);
        m_taInputMatrix.setColumns(20);
        m_taInputMatrix.setLineWrap(true);
        m_taInputMatrix.setRows(5);
        m_taInputMatrix.setMinimumSize(new java.awt.Dimension(0, 16));
        jScrollPane1.setViewportView(m_taInputMatrix);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_MatrixSizeX.setToolTipText("X Size of Matrix");
        tb_MatrixSizeX.setMinimumSize(new java.awt.Dimension(100, 28));
        tb_MatrixSizeX.setPreferredSize(new java.awt.Dimension(100, 28));

        tb_MatrixSizeY.setToolTipText("Y Size of Matrix");
        tb_MatrixSizeY.setMinimumSize(new java.awt.Dimension(100, 28));
        tb_MatrixSizeY.setPreferredSize(new java.awt.Dimension(100, 28));

        lbl_MatrixY.setText("Matrix Y");

        lbl_MatrixX.setText("Matrix X");

        m_taInputMatrix.setEditable(false);
        m_taInputMatrix.setColumns(20);
        m_taInputMatrix.setLineWrap(true);
        m_taInputMatrix.setRows(5);
        m_taInputMatrix.setMinimumSize(new java.awt.Dimension(0, 16));
        jScrollPane1.setViewportView(m_taInputMatrix);

        ta_OutputMatrix.setEditable(false);
        ta_OutputMatrix.setColumns(20);
        ta_OutputMatrix.setRows(5);
        jScrollPane2.setViewportView(ta_OutputMatrix);

        btn_setMatrixSize.setText("Set Matrix Size");
        btn_setMatrixSize.setMinimumSize(new java.awt.Dimension(25, 29));
        btn_setMatrixSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setMatrixSizeActionPerformed(evt);
            }
        });

        btn_setMatrixSize1.setText("Set Values");
        btn_setMatrixSize1.setMinimumSize(new java.awt.Dimension(25, 29));
        btn_setMatrixSize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setMatrixSize1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_MatrixY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tb_MatrixSizeY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_MatrixX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tb_MatrixSizeX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_setMatrixSize, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_setMatrixSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tb_MatrixSizeX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_MatrixX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tb_MatrixSizeY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_MatrixY)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_setMatrixSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_setMatrixSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btn_setMatrixSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setMatrixSizeActionPerformed
      if(checkValue()){
          BFS.setAdjacenyMatrix(matrixX, matrixY);
          m_taInputMatrix.enableInputMethods(true);
          
      }else
      {
          String errorMessage = "MatrixX and MatrixY, must be greater than or equal to zero";
          JOptionPane.showMessageDialog(null, errorMessage,"Error",JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_btn_setMatrixSizeActionPerformed

    private void btn_setMatrixSize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setMatrixSize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_setMatrixSize1ActionPerformed

    protected boolean checkValue(){
        matrixX = Integer.parseInt(tb_MatrixSizeX.getText());
        matrixY = Integer.parseInt(tb_MatrixSizeY.getText());
        
        if(matrixX >=1 || matrixY >= 1)
            return true;
        else 
            return false;     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BreadthFirstSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BreadthFirstSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BreadthFirstSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BreadthFirstSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BreadthFirstSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_setMatrixSize;
    private javax.swing.JButton btn_setMatrixSize1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_MatrixX;
    private javax.swing.JLabel lbl_MatrixY;
    private javax.swing.JTextArea m_taInputMatrix;
    private javax.swing.JTextArea ta_OutputMatrix;
    private javax.swing.JTextField tb_MatrixSizeX;
    private javax.swing.JTextField tb_MatrixSizeY;
    // End of variables declaration//GEN-END:variables
}
